# Header
menu:
  Home: /
  Lightning: /lightning
  Heroku Workshop: /heroku-workshop
  Salesforce Developers: https://developer.salesforce.com
  jr0cket: http://jr0cket.co.uk
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tagcloud



# Miscellaneous
google_analytics: UA-28030709-5 
favicon: /favicon.png
twitter: agileforce 
google_plus:
fb_admins:
fb_app_id: