# Header
menu:
  Home: /
  DevGuides: http://jr0cket.co.uk/developer-guides
  Slides:    http://jr0cket.co.uk/slides
  Workshops: /workshops
  Clojure: /clojure
  Hexo: /hexo
  Ubuntu: http://ubuntu.jr0cket.co.uk
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tagcloud



# Miscellaneous
google_analytics: UA-28030709-2
favicon: /favicon.png
twitter: jr0cket 
google_plus:
fb_admins:
fb_app_id: