# Header
menu:
  Home: /
  Heroku Workshop: /heroku-workshop
  Developers: https://developer.salesforce.com
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tagcloud



# Miscellaneous
google_analytics: UA-28030709-2
favicon: /favicon.png
twitter: agileforce 
google_plus:
fb_admins:
fb_app_id: